# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('view_myuser', 'Can see available myuser'),)},
        ),
    ]
