# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-13 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170512_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '\u6269\u5c55\u7528\u6237'},
        ),
    ]
