# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170513_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='headimg',
            field=models.ImageField(blank=True, default=b'static/accounts/img/default.png', null=True, upload_to=b'static/accounts/img'),
        ),
    ]
